# Generated by Django 5.0.6 on 2024-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(max_length=128),
        ),
    ]
