# Generated by Django 5.0.6 on 2024-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_user_name_alter_order_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
